# Title: Data Cleaning for Survery Results
# Name: Maxwell Yung
# Date: 2/23/25

Import pandas, read in file

In [1]:
import pandas as pd
datafile = "Non-Majors Survey Results - Fall 2024.csv"
df = pd.read_csv(datafile)

Explore dataset using built in functions of pandas

In [ ]:
df

In [ ]:
df.describe

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df.dtypes

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.sample()

In [ ]:
df.info()

## Now we need to clean up the data. First, we'll start with renaming columns (code from GitHub CoPilot)

This is the dataset + columns before any manipulation

In [2]:
df

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2024/09/20 10:55:34 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,Yes,No,No,No,No,...,Yes,No,No,No,Yes,Yes,No,Woman,Hispanic or Latino;White/Caucasian,21-24
88,2024/09/20 11:02:45 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,No,No,No,No,No,Woman,Hispanic or Latino,19-20
89,2024/09/20 11:07:16 PM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,Yes,No,No,No,...,No,No,No,Yes,No,Yes,No,Woman,Black/African American,19-20
90,2024/09/21 5:06:23 PM AST,CMP 101 Computer Information Literacy,No,Yes,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,Hispanic or Latino,19-20
91,2024/09/22 10:08:19 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,Yes,No,No,Yes,Woman,Asian,21-24

In [3]:
df.columns

Index(['Timestamp', 'Which course are you currently enrolled in?',
       'What motivated you to seek a computing class at CCM? [It’s a required class for the degree I’m seeking]',
       'What motivated you to seek a computing class at CCM? [To keep current in computing skills]',
       'What motivated you to seek a computing class at CCM? [Career Advancement]',
       'What motivated you to seek a computing class at CCM? [Career Change]',
       'What motivated you to seek a computing class at CCM? [Professional Development]',
       'What motivated you to seek a computing class at CCM? [Job Displacement]',
       'What motivated you to seek a computing class at CCM? [Relocation]',
       'What motivated you to seek a computing class at CCM? [IT Industry Certifications]',
       'What motivated you to seek a computing class at CCM? [Financial]',
       'What motivated you to seek a computing class at CCM? [Personal Enrichment]',
       'What motivated you to seek a computing class at CCM? [Curiosity]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]',
       'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]',
       'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]',
       'How did you hear about County College of Morris  [CCM Web site]',
       'How did you hear about County College of Morris  [Billboard]',
       'How did you hear about County College of Morris  [Television]',
       'How did you hear about County College of Morris  [Radio]',
       'How did you hear about County College of Morris  [Social Media]',
       'How did you hear about County College of Morris  [Community Event]',
       'How did you hear about County College of Morris  [Family member or friend]',
       'How did you hear about County College of Morris  [Employer]',
       'How did you hear about County College of Morris  [Current student]',
       'How did you hear about County College of Morris  [Alumni]',
       'How did you hear about County College of Morris  [High School]',
       'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]',
       'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]',
       'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]',
       'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]',
       'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]',
       'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]',
       'To what extent did the following impact your decision to attend County College of Morris? [College reputation]',
       'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]',
       'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]',
       'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]',
       'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]',
       'What degree program are you currently enrolled in?',
       'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]',
       'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]',
       'Did you receive information about our computing course from any of the following sources? [CCM Admissions]',
       'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]',
       'Did you receive information about our computing course from any of the following sources? [Employer]',
       'Did you receive information about our computing course from any of the following sources? [Other]',
       'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]',
       'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]',
       'Gender', 'Race/ethnicity', 'Age '],
      dtype='object')

Now, we manipulate the data, making the column names shorter

In [4]:
new_columns = {
    'Timestamp': 'timestamp',
    'Which course are you currently enrolled in?': 'current_course',
    'What motivated you to seek a computing class at CCM? [It‚Äôs a required class for the degree I‚Äôm seeking]': 'required',
    'What motivated you to seek a computing class at CCM? [To keep current in computing skills]': 'current',
    'What motivated you to seek a computing class at CCM? [Career Advancement]': 'advancement',
    'What motivated you to seek a computing class at CCM? [Career Change]': 'change',
    'What motivated you to seek a computing class at CCM? [Professional Development]': 'development',
    'What motivated you to seek a computing class at CCM? [Job Displacement]': 'displacement',
    'What motivated you to seek a computing class at CCM? [Relocation]': 'relocation',
    'What motivated you to seek a computing class at CCM? [IT Industry Certifications]': 'certifications',
    'What motivated you to seek a computing class at CCM? [Financial]': 'financial',
    'What motivated you to seek a computing class at CCM? [Personal Enrichment]': 'enrichment',
    'What motivated you to seek a computing class at CCM? [Curiosity]': 'curiosity',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]': 'openhouse',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]': 'instant_decision',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]': 'oncampus_session',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan\'s Tuesday Virtual Information Session]': 'titans_tuesday',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]': 'women_dare',
    'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]': 'college_fair',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]': 'hs_class',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]': 'hs_club',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]': 'competitions',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]': 'afterschool',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]': 'summer_camp',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]': 'ap_class',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]': 'dual_enrollment',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]': 'family_influence',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]': 'family_field',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]': 'counselor',
    'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]': 'employer',
    'How did you hear about County College of Morris  [CCM Web site]': 'website',
    'How did you hear about County College of Morris  [Billboard]': 'billboard',
    'How did you hear about County College of Morris  [Television]': 'tv',
    'How did you hear about County College of Morris  [Radio]': 'radio',
    'How did you hear about County College of Morris  [Social Media]': 'social',
    'How did you hear about County College of Morris  [Community Event]': 'event',
    'How did you hear about County College of Morris  [Family member or friend]': 'word_of_mouth',
    'How did you hear about County College of Morris  [Employer]': 'employer_ccm',
    'How did you hear about County College of Morris  [Current student]': 'current_student',
    'How did you hear about County College of Morris  [Alumni]': 'alumni',
    'How did you hear about County College of Morris  [High School]': 'high_school',
    'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]': 'cost',
    'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]': 'location',
    'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]': 'programs',
    'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]': 'online',
    'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]': 'referral',
    'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]': 'faculty',
    'To what extent did the following impact your decision to attend County College of Morris? [College reputation]': 'reputation',
    'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]': 'scholarships',
    'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]': 'transfer',
    'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]': 'class_size',
    'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]': 'activities',
    'What degree program are you currently enrolled in?': 'degree_program',
    'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]': 'counselor_info',
    'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]': 'ccm_it_website',
    'Did you receive information about our computing course from any of the following sources? [CCM Admissions]': 'admissions',
    'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]': 'ccm_counselor',
    'Did you receive information about our computing course from any of the following sources? [Employer]': 'employer_course',
    'Did you receive information about our computing course from any of the following sources? [Other]': 'other_info',
    'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?': 'interest_level',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]': 'web',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]': 'cybersecurity',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]': 'apps',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]': 'analytics',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]': 'ml_ai',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]': 'programming',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]': 'gamedev',
    'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]': 'hardware',
    'Gender': 'gender',
    'Race/ethnicity': 'race_ethnicity',
    'Age ': 'age'
}

df.rename(columns=new_columns, inplace=True)
df.rename(columns={df.columns[2]: 'required'}, inplace=True) #we need to specifically rename this column because of the apostrophe. for some reason, Äôm doesn't register in the dictionary so this is the last resort

Dataset + columns AFTER manipulation:

In [5]:
df

,timestamp,current_course,required,current,advancement,change,development,displacement,relocation,certifications,...,cybersecurity,apps,analytics,ml_ai,programming,gamedev,hardware,gender,race_ethnicity,age
0,2024/09/10 10:47:35 AM AST,CMP 126 Computer Technology and Applications,No,Yes,Yes,Yes,Yes,No,No,No,...,Yes,No,No,No,No,No,No,Prefer not to say,Hispanic or Latino;Black/African American;Whit...,19-20
1,2024/09/10 11:00:05 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,Yes,Yes,Yes,No,No,Woman,Hispanic or Latino,19-20
2,2024/09/10 11:02:51 AM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,Yes,Yes,Yes,Yes,Man,Choose not to reply,18 and younger
3,2024/09/10 11:05:25 AM AST,CMP 126 Computer Technology and Applications,No,Yes,No,No,No,No,No,No,...,No,No,Yes,No,No,Yes,No,Man,Hispanic or Latino,19-20
4,2024/09/10 8:37:36 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,19-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2024/09/20 10:55:34 PM AST,CMP 101 Computer Information Literacy,Yes,Yes,Yes,Yes,No,No,No,No,...,Yes,No,No,No,Yes,Yes,No,Woman,Hispanic or Latino;White/Caucasian,21-24
88,2024/09/20 11:02:45 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,Yes,No,No,...,Yes,Yes,No,No,No,No,No,Woman,Hispanic or Latino,19-20
89,2024/09/20 11:07:16 PM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,Yes,No,No,No,...,No,No,No,Yes,No,Yes,No,Woman,Black/African American,19-20
90,2024/09/21 5:06:23 PM AST,CMP 101 Computer Information Literacy,No,Yes,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,Hispanic or Latino,19-20
91,2024/09/22 10:08:19 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,Yes,No,Yes,No,No,No,...,No,No,No,Yes,No,No,Yes,Woman,Asian,21-24

In [6]:
df.columns

Index(['timestamp', 'current_course', 'required', 'current', 'advancement',
       'change', 'development', 'displacement', 'relocation', 'certifications',
       'financial', 'enrichment', 'curiosity', 'openhouse', 'instant_decision',
       'oncampus_session', 'titans_tuesday', 'women_dare', 'college_fair',
       'hs_class', 'hs_club', 'competitions', 'afterschool', 'summer_camp',
       'ap_class', 'dual_enrollment', 'family_influence', 'family_field',
       'counselor', 'employer', 'website', 'billboard', 'tv', 'radio',
       'social', 'event', 'word_of_mouth', 'employer_ccm', 'current_student',
       'alumni', 'high_school', 'cost', 'location', 'programs', 'online',
       'referral', 'faculty', 'reputation', 'scholarships', 'transfer',
       'class_size', 'activities', 'degree_program', 'counselor_info',
       'ccm_it_website', 'admissions', 'ccm_counselor', 'employer_course',
       'other_info', 'interest_level', 'web', 'cybersecurity', 'apps',
       'analytics', 'ml_ai', 'programming', 'gamedev', 'hardware', 'gender',
       'race_ethnicity', 'age'],
      dtype='object')

## Let's get rid of unneccesary columns

Question 1: Are students that have taken a computing class prior to their CCM education more likely to voluntarily take a computing class at CCM? (hs_class, ap_class, dual_enrollment, interest_level)

Question 2: Which class is the most likely to be taken for someone's passion (personal enrichment or curiosity)? (current_course, enrichment, curiosity)

Question 3: Which programs have the most students who are enthusiastic about computer science? (interest_level, degree_program)

Question 4: Which specific computer science classes have the most interest? (web, cybersecurity, apps, analytics, ml_ai, programming, gamedev, hardware, interest_level)

Question 5: What age group is the least enthusiastic about computer science? (age, interest_level)

Columns needed: 
hs_class, ap_class, dual_enrollment, interest_level, current_course, enrichment, curiosity, degree_program, age, web, cybersecurity, apps, analytics, ml_ai, programming, gamedev, hardware

In [8]:
keep = ['hs_class', 'ap_class', 'dual_enrollment', 'interest_level', 'current_course', 'enrichment', 'curiosity', 'degree_program', 'age', 'web', 'cybersecurity', 'apps', 'analytics', 'ml_ai', 'programming', 'gamedev', 'hardware']
df_sub = df[keep]

Now, here is the final csv file and columns

In [9]:
df_sub

,hs_class,ap_class,dual_enrollment,interest_level,current_course,enrichment,curiosity,degree_program,age,web,cybersecurity,apps,analytics,ml_ai,programming,gamedev,hardware
0,No Impact,NaN,NaN,2,CMP 126 Computer Technology and Applications,Yes,Yes,Liberal Arts,19-20,Yes,Yes,No,No,No,No,No,No
1,Some Impact,Some Impact,Some Impact,3,CMP 126 Computer Technology and Applications,Yes,Yes,child psychology,19-20,No,Yes,Yes,Yes,Yes,Yes,No,No
2,NaN,NaN,NaN,5,CMP 126 Computer Technology and Applications,No,No,Broadcasting Arts and Technology,18 and younger,Yes,No,Yes,No,Yes,Yes,Yes,Yes
3,No Impact,No Impact,No Impact,3,CMP 126 Computer Technology and Applications,No,No,analyst,19-20,No,No,No,Yes,No,No,Yes,No
4,Some Impact,NaN,NaN,3,CMP 101 Computer Information Literacy,Yes,Yes,Journalism,19-20,No,No,No,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Some Impact,Some Impact,High Impact,3,CMP 101 Computer Information Literacy,No,Yes,Early Childhood Education,21-24,No,Yes,No,No,No,Yes,Yes,No
88,No Impact,No Impact,No Impact,3,CMP 126 Computer Technology and Applications,Yes,Yes,Liberal Arts,19-20,Yes,Yes,Yes,No,No,No,No,No
89,No Impact,No Impact,No Impact,1,CMP 126 Computer Technology and Applications,No,No,Liberal Arts,19-20,No,No,No,No,Yes,No,Yes,No
90,High Impact,No Impact,No Impact,3,CMP 101 Computer Information Literacy,No,Yes,Nursing,19-20,No,No,No,No,No,No,No,No
91,Some Impact,No Impact,No Impact,5,CMP 126 Computer Technology and Applications,Yes,Yes,Child and Family Studies,21-24,No,No,No,No,Yes,No,No,Yes

In [10]:
df_sub.columns

Index(['hs_class', 'ap_class', 'dual_enrollment', 'interest_level',
       'current_course', 'enrichment', 'curiosity', 'degree_program', 'age',
       'web', 'cybersecurity', 'apps', 'analytics', 'ml_ai', 'programming',
       'gamedev', 'hardware'],
      dtype='object')

In [ ]:
df_sub.to_csv('cleaned.csv')

p.s. does the degree program column really need to be cleaned up if there are no similar majors?